### ISSUE TITLE
Black screen issue with screen protector

### ISSUE THREAD

**Issue by midhunpmohan** [RyukieSama/Swifty#2]
When we try to setting **self.view = ScreenShieldView.create()** then the entire screen is changed to black even before taking screenshot

**Comment by RyukieSama** [comment]
> When we try to setting **self.view = ScreenShieldView.create()** then the entire screen is changed to black even before taking screenshot

Did you use it in a UIViewController`s `loadView` function or some where else?
If you can tell me the version of system which this problem appear, it will be helpful.

**Comment by midhunpmohan** [comment]
I tried like this
<img width="737" alt="Screenshot 2022-02-24 at 8 35 49 AM" src="https://user-images.githubusercontent.com/35839262/155479116-405815cf-d64f-4134-bced-bbf589acb2cf.png">
d

Xcode 13
iOS 15

**Comment by RyukieSama** [comment]
> I tried like this <img alt="Screenshot 2022-02-24 at 8 35 49 AM" width="737" src="https://user-images.githubusercontent.com/35839262/155479116-405815cf-d64f-4134-bced-bbf589acb2cf.png">
> 
> Xcode 13 iOS 15


I see.
If you want to change the root view of a controller, you should do it like this, not in `viewDidLoad` :

```Swift
import UIKit
import RyukieSwifty

class ViewController: UIViewController {
    override func loadView() {
        view = ScreenShieldView.create()
    }
    ...
}
```

**Comment by midhunpmohan** [comment]
Still facing the same black screen issue even with your sample demo project also.
![IMG_EB6A108664DD-1](https://user-images.githubusercontent.com/35839262/155487540-0220acc1-369f-4476-9d96-b56fd7e52f8a.jpeg)

**Comment by RyukieSama** [comment]
The example project has been updated.
You can see `ScreenShieldViewController.swift` for more detail. 
It works well.
