### ISSUE TITLE
某些设备：[NSCountableTextLocation compare:] 

### ISSUE THREAD

**Issue by YanChen-ing** [RyukieSama/Swifty#3]
发现 在 有一台 iphone 11 pro，iOS 15.1， 有崩溃
可用模拟器复现：
CoreSimulator 776.4 - Device: iPhone 13 (9CAB0B24-C444-409B-9E5E-50A9EFD7CF8B) - Runtime: iOS 15.0 (19A339) - DeviceType: iPhone 13

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCountableTextLocation compare:] receiving unmatching type (null)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff203fbbb4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff2019ebe7 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff203fba92 -[NSException initWithCoder:] + 0
	3   UIFoundation                        0x00007fff24298433 -[NSCountableTextLocation compare:] + 200
	4   UIFoundation                        0x00007fff242d1ac5 -[NSTextViewportLayoutController layoutViewport] + 2025
	5   UIKitCore                           0x00007fff255af1fe +[UIView(Animation) performWithoutAnimation:] + 84
	6   UIKitCore                           0x00007fff24a50bb0 -[_UITextLayoutCanvasView layoutSubviews] + 97
	7   UIKitCore                           0x00007fff255bcaad -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2962
	8   QuartzCore                          0x00007fff2893c2b6 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 548
	9   QuartzCore                          0x00007fff289474f1 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	10  QuartzCore                          0x00007fff288830ca _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 652
	11  QuartzCore                          0x00007fff288bac47 _ZN2CA11Transaction6commitEv + 699
	12  UIKitCore                           0x00007fff24ffa814 _UIApplicationFlushRunLoopCATransactionIfTooLate + 70
	13  UIKitCore                           0x00007fff250b3e36 __processEventQueue + 9641

**Comment by GrapeFruitJun** [comment]
+1

**Comment by RyukieSama** [comment]
针对特定系统做了屏蔽，暂时没有更好的解决方案，特定系统下会失去防护效果，就是一个普通的UIView。

**Comment by CallMUSE** [comment]
经测试某些行为导致重新layout的时候会出现

**Comment by YanChen-ing** [comment]
iOS 15.0 +, 使用 _UITextLayoutCanvasView， 在布局的时候，私有类 [NSCountableTextLocation compare]，判空错误，我用运行时替换了实现可行

**Comment by RyukieSama** [comment]
> iOS 15.0 +, 使用 _UITextLayoutCanvasView， 在布局的时候，私有类 [NSCountableTextLocation compare]，判空错误，我用运行时替换了实现可行

直接使用私有类上架有风险。你有上架没？

**Comment by RyukieSama** [comment]
> 



> 经测试某些行为导致重新layout的时候会出现

能举个例子么？

**Comment by YanChen-ing** [comment]
> > iOS 15.0 +, 使用 _UITextLayoutCanvasView， 在布局的时候，私有类 [NSCountableTextLocation compare]，判空错误，我用运行时替换了实现可行
> 
> 直接使用私有类上架有风险。你有上架没？

通过审核，上架了，目前还好，但风险肯定还是有的
