### ISSUE TITLE
ScreenShieldView使用insertSubview添加view防截屏效果失效

### ISSUE THREAD

**Issue by MuXingX** [RyukieSama/Swifty#4]
在使用ScreenShieldView创建出来的view中，如果是insertSubview一个子view的话，insertSubview进来的子view还是能被截屏到了。如：
self.view = [ScreenShieldView createWithFrame:UIScreen.mainScreen.bounds];
UIView *insetView = [[UIView alloc] initWithFrame:CGRectMake(30, 80, 180, 280)];
insetView.backgroundColor = [UIColor redColor];
[self.view insertSubview:insetView atIndex:0];
截图后insetView仍然会被截屏保留。

**Comment by RyukieSama** [comment]
多谢反馈，我看看

**Comment by RyukieSama** [comment]
更新下了版本，重写了相关方法
